templates:
  daily_sales:
    type: pdf
    sections:
      - title: "Executive Summary"
        metrics:
          - total_revenue
          - transaction_count
          - avg_transaction_value
      - title: "Customer Analysis"
        metrics:
          - active_customers
          - new_customers
          - retention_rate
      - title: "Product Performance"
        metrics:
          - top_products
          - category_breakdown

schedule:
  daily_report:
    template: daily_sales
    schedule: "0 6 * * *"
    recipients:
      - "sales@company.com"
      - "management@company.com"

distribution:
  email:
    smtp_host: "${SMTP_HOST}"
    smtp_port: 587
    username: "${SMTP_USER}"
    password: "${SMTP_PASS}"
    from_email: "reports@company.com" 