version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: feature_store
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
  feast:
    build:
      context: .
      dockerfile: docker/feast/Dockerfile
    depends_on:
      - redis
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    depends_on:
      - feast
      - redis
    ports:
      - "8000:8000"
    environment:
      - FEAST_REDIS_HOST=redis
      - FEAST_REDIS_PORT=6379
      
  airflow:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
      
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  redis_data:
  airflow_logs:
  grafana_data: 